/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : eMIOS_Pwm1.h
**     Project     : emios_pwm_mpc5748g
**     Processor   : MPC5748G_176
**     Component   : emios_pwm
**     Version     : Component SDK_S32_PA_11, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32_PA_11
**     Compiler    : GNU C Compiler
**     Date/Time   : 2020-07-15, 15:55, # CodeGen: 0
**     Contents    :
**         EMIOS_DRV_PWM_InitMode                     - status_t EMIOS_DRV_PWM_InitMode(uint8_t emiosGroup, uint8_t channel,...
**         EMIOS_DRV_PWM_ForcePWMMatchLeadingEdge     - void EMIOS_DRV_PWM_ForcePWMMatchLeadingEdge(uint8_t emiosGroup, uint8_t...
**         EMIOS_DRV_PWM_ForcePWMMatchTrailingEdge    - void EMIOS_DRV_PWM_ForcePWMMatchTrailingEdge(uint8_t emiosGroup, uint8_t...
**         EMIOS_DRV_PWM_GetPeriod                    - uint32_t EMIOS_DRV_PWM_GetPeriod(uint8_t emiosGroup, uint8_t channel);
**         EMIOS_DRV_PWM_SetPeriod                    - void EMIOS_DRV_PWM_SetPeriod(uint8_t emiosGroup, uint8_t channel, uint32_t...
**         EMIOS_DRV_PWM_GetDutyCycle                 - uint32_t EMIOS_DRV_PWM_GetDutyCycle(uint8_t emiosGroup, uint8_t channel);
**         EMIOS_DRV_PWM_SetDutyCycle                 - status_t EMIOS_DRV_PWM_SetDutyCycle(uint8_t emiosGroup, uint8_t channel,...
**         EMIOS_DRV_PWM_GetLeadingEdgePlacement      - uint32_t EMIOS_DRV_PWM_GetLeadingEdgePlacement(uint8_t emiosGroup, uint8_t...
**         EMIOS_DRV_PWM_SetLeadingEdgePlacement      - void EMIOS_DRV_PWM_SetLeadingEdgePlacement(uint8_t emiosGroup, uint8_t...
**         EMIOS_DRV_PWM_GetTrailingEdgePlacement     - uint32_t EMIOS_DRV_PWM_GetTrailingEdgePlacement(uint8_t emiosGroup, uint8_t...
**         EMIOS_DRV_PWM_SetTrailingEdgePlacement     - void EMIOS_DRV_PWM_SetTrailingEdgePlacement(uint8_t emiosGroup, uint8_t...
**         EMIOS_DRV_PWM_SetCenterAlignDeadTime       - void EMIOS_DRV_PWM_SetCenterAlignDeadTime(uint8_t emiosGroup, uint8_t...
**         EMIOS_DRV_PWM_GetCenterAlignDeadTime       - uint32_t EMIOS_DRV_PWM_GetCenterAlignDeadTime(uint8_t emiosGroup, uint8_t...
**         EMIOS_DRV_PWM_SetCenterAlignIdealDutyCycle - void EMIOS_DRV_PWM_SetCenterAlignIdealDutyCycle(uint8_t emiosGroup, uint8_t...
**         EMIOS_DRV_PWM_GetCenterAlignIdealDutyCycle - uint32_t EMIOS_DRV_PWM_GetCenterAlignIdealDutyCycle(uint8_t emiosGroup,...
**         EMIOS_DRV_PWM_SetTriggerPlacement          - void EMIOS_DRV_PWM_SetTriggerPlacement(uint8_t emiosGroup, uint8_t channel,...
**         EMIOS_DRV_PWM_GetTriggerPlacement          - uint32_t EMIOS_DRV_PWM_GetTriggerPlacement(uint8_t emiosGroup, uint8_t channel);
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file eMIOS_Pwm1.h
** @version 01.00
*/         
/*!
**  @addtogroup eMIOS_Pwm1_module eMIOS_Pwm1 module documentation
**  @{
*/         
#ifndef eMIOS_Pwm1_H
#define eMIOS_Pwm1_H

/* MODULE eMIOS_Pwm1.
 *
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 2.5, Global macro not referenced.
 * The global macro will be used in function call of the module.
 */

#include "emios_common.h"
#include "emios_mc_driver.h"
#include "emios_pwm_driver.h"
#include "eMIOS_Mc1.h"
#include "Cpu.h"


/* eMIOS PWM channel for eMIOS_0 */
#define EMIOS_PWM1_CHANNEL23    (23U)

/* eMIOS PWM mode configuration structure for eMIOS_0 */
extern const emios_pwm_param_t eMIOS_Pwm1_PWMChnConfig0;

#endif /* ifndef eMIOS_Pwm1_H */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
